#!/usr/bin/env node
/**
 * Builds design tokens from tokens/*.json (W3C DTCG format) into:
 *   generated/tokens.css   CSS custom properties (--ug-*) for the web app
 *   generated/tokens.js    JS module for React Native + web (numbers for dimensions)
 *   generated/tokens.d.ts  Types for tokens.js
 *   generated/tokens.json  Flat resolved map, handy for tooling / Figma plugins
 *
 * Usage:
 *   node scripts/build.mjs          write generated files
 *   node scripts/build.mjs --check  exit 1 if generated files are stale
 */
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const tokensDir = path.join(root, "tokens");
const outDir = path.join(root, "generated");
const CSS_PREFIX = "ug";
const HEADER = "Generated by @ug-cs/design-tokens. Do not edit; change tokens/*.json and run `pnpm tokens:build`.";

// ---------- load + flatten ----------

async function loadTokens() {
  const files = (await readdir(tokensDir)).filter((f) => f.endsWith(".json")).sort();
  const merged = {};
  for (const file of files) {
    const json = JSON.parse(await readFile(path.join(tokensDir, file), "utf8"));
    for (const [key, value] of Object.entries(json)) {
      if (key in merged) throw new Error(`Duplicate top-level group "${key}" in ${file}`);
      merged[key] = value;
    }
  }
  return merged;
}

/** Walks the DTCG tree and returns [{ path: string[], type, value, description }]. */
function flatten(node, trail = [], inheritedType) {
  const type = node.$type ?? inheritedType;
  if ("$value" in node) {
    if (!type) throw new Error(`Token ${trail.join(".")} has no $type`);
    return [{ path: trail, type, value: node.$value, description: node.$description }];
  }
  return Object.entries(node)
    .filter(([key]) => !key.startsWith("$"))
    .flatMap(([key, child]) => flatten(child, [...trail, key], type));
}

function resolveAliases(tokens) {
  const byName = new Map(tokens.map((t) => [t.path.join("."), t]));
  const resolve = (token, seen = new Set()) => {
    const match = typeof token.value === "string" && token.value.match(/^\{(.+)\}$/);
    if (!match) return token.value;
    const name = token.path.join(".");
    if (seen.has(name)) throw new Error(`Circular alias at ${name}`);
    const target = byName.get(match[1]);
    if (!target) throw new Error(`Unknown alias {${match[1]}} in ${name}`);
    return resolve(target, new Set([...seen, name]));
  };
  return tokens.map((t) => ({ ...t, value: resolve(t) }));
}

// ---------- validation ----------

const COLOR_RE = /^(#([0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})|rgba?\(.+\)|hsla?\(.+\)|oklch\(.+\))$/i;

function validate(tokens) {
  const errors = [];
  for (const t of tokens) {
    const name = t.path.join(".");
    if (t.type === "color" && !COLOR_RE.test(t.value)) errors.push(`${name}: invalid color "${t.value}"`);
    if (t.type === "dimension" && (typeof t.value?.value !== "number" || !["px", "rem"].includes(t.value?.unit)))
      errors.push(`${name}: dimension must be { value: number, unit: "px" | "rem" }`);
    if (t.type === "fontWeight" && typeof t.value !== "number") errors.push(`${name}: fontWeight must be a number`);
  }
  if (errors.length) throw new Error(`Invalid tokens:\n  ${errors.join("\n  ")}`);
}

// ---------- formatters ----------

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const cssVar = (t) => `--${CSS_PREFIX}-${t.path.map(kebab).join("-")}`;

function cssValue(t) {
  switch (t.type) {
    case "dimension":
      return `${t.value.value}${t.value.unit}`;
    case "fontFamily":
      return (Array.isArray(t.value) ? t.value : [t.value]).map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(", ");
    default:
      return String(t.value);
  }
}

/** JS values target React Native: dimensions become unitless numbers (px). */
function jsValue(t) {
  if (t.type === "dimension") return t.value.unit === "rem" ? t.value.value * 16 : t.value.value;
  return t.value;
}

function toNested(tokens, valueOf) {
  const out = {};
  for (const t of tokens) {
    let node = out;
    t.path.slice(0, -1).forEach((key) => (node = node[key] ??= {}));
    node[t.path.at(-1)] = valueOf(t);
  }
  return out;
}

function formatCss(tokens) {
  const lines = tokens.map((t) => `  ${cssVar(t)}: ${cssValue(t)};`);
  return `/* ${HEADER} */\n:root {\n${lines.join("\n")}\n}\n`;
}

function formatJs(tokens) {
  const nested = toNested(tokens, jsValue);
  const exports = Object.entries(nested).map(
    ([group, value]) => `export const ${group} = ${JSON.stringify(value, null, 2)};`,
  );
  const all = `export const tokens = { ${Object.keys(nested).join(", ")} };\nexport default tokens;`;
  return `// ${HEADER}\n\n${exports.join("\n\n")}\n\n${all}\n`;
}

function formatDts(tokens) {
  const nested = toNested(tokens, jsValue);
  const literal = (v, indent) => {
    if (Array.isArray(v)) return `readonly [${v.map((x) => JSON.stringify(x)).join(", ")}]`;
    if (v && typeof v === "object") {
      const pad = "  ".repeat(indent + 1);
      const body = Object.entries(v)
        .map(([k, x]) => `${pad}readonly ${/^[a-z_$][\w$]*$/i.test(k) ? k : JSON.stringify(k)}: ${literal(x, indent + 1)};`)
        .join("\n");
      return `{\n${body}\n${"  ".repeat(indent)}}`;
    }
    return JSON.stringify(v);
  };
  const decls = Object.entries(nested).map(([group, value]) => `export declare const ${group}: ${literal(value, 0)};`);
  const groups = Object.keys(nested);
  const all = `export declare const tokens: {\n${groups.map((g) => `  readonly ${g}: typeof ${g};`).join("\n")}\n};\nexport default tokens;`;
  const aliases = [
    "export type ColorToken = keyof typeof color;",
    "export type RadiusToken = keyof typeof radius;",
  ].filter((line) => groups.some((g) => line.includes(`typeof ${g};`)));
  return `// ${HEADER}\n\n${decls.join("\n\n")}\n\n${all}\n\n${aliases.join("\n")}\n`;
}

function formatJson(tokens) {
  const flat = Object.fromEntries(
    tokens.map((t) => [t.path.join("."), { type: t.type, value: t.value, css: cssVar(t), ...(t.description && { description: t.description }) }]),
  );
  return `${JSON.stringify(flat, null, 2)}\n`;
}

// ---------- main ----------

async function main() {
  const check = process.argv.includes("--check");
  const tokens = resolveAliases(flatten(await loadTokens()));
  validate(tokens);

  const outputs = {
    "tokens.css": formatCss(tokens),
    "tokens.js": formatJs(tokens),
    "tokens.d.ts": formatDts(tokens),
    "tokens.json": formatJson(tokens),
  };

  if (check) {
    const stale = [];
    for (const [file, content] of Object.entries(outputs)) {
      const target = path.join(outDir, file);
      if (!existsSync(target) || (await readFile(target, "utf8")) !== content) stale.push(file);
    }
    if (stale.length) {
      console.error(`✖ Design tokens are out of date: ${stale.join(", ")}\n  Run \`pnpm tokens:build\` and commit the result.`);
      process.exit(1);
    }
    console.log(`✔ Design tokens up to date (${tokens.length} tokens)`);
    return;
  }

  await mkdir(outDir, { recursive: true });
  await Promise.all(Object.entries(outputs).map(([file, content]) => writeFile(path.join(outDir, file), content)));
  console.log(`✔ Built ${tokens.length} tokens → ${path.relative(process.cwd(), outDir) || "."}/{${Object.keys(outputs).join(",")}}`);
}

main().catch((err) => {
  console.error(`✖ ${err.message}`);
  process.exit(1);
});
